version: "3.8"

services:
  n8n:
    image: n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=supersecreto123
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - ./n8n_data:/home/node/.n8n

  django:
    build: ../django_api
    container_name: simple_django_api
    ports:
      - "8000:8000"
    volumes:
      - ../django_api:/app
    working_dir: /app
    environment:
      - PYTHONUNBUFFERED=1
      - DB_HOST=postgres_simple
      - DB_PORT=5432
      - DB_NAME=simple_db
      - DB_USER=simple_user
      - DB_PASSWORD=simple_pass

  ngrok_django:
    image: ngrok/ngrok:latest
    container_name: ngrok_django
    restart: unless-stopped
    environment:
      - NGROK_AUTHTOKEN=TU_AUTHTOKEN_AQUI
      - NGROK_REGION=us
      - NGROK_TUNNELS=django
      - NGROK_TUNNELS_DJANGO_ADDR=simple_django_api:8000
      - NGROK_TUNNELS_DJANGO_PROTO=http

  php_server:
    image: php:8.2-apache
    container_name: php_server
    ports:
      - "8080:80"
    volumes:
      - ./php_server:/var/www/html

  postgres_simple:
    image: postgres:15
    container_name: postgres_simple
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: simple_db
      POSTGRES_USER: simple_user
      POSTGRES_PASSWORD: simple_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
